build:
  dependencies:
    before:
    - "composer install"
  environment:
    php:
      version: 7.2
  tests:
    override:
    - php-scrutinizer-run
    - command: phpcs-run ./app
checks:
  php:
    code_rating: true
    duplication: true
    fix_doc_comments: true
    fix_identation_4spaces: true
    fix_line_ending: true
    fix_linefeed: true
    fix_php_opening_tag: true
    fix_use_statements:
      order_alphabetically: true
      preserve_blanklines: true
      preserve_multiple: false
      remove_unused: true
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
filter:
  excluded_paths:
  - tests/*
  - vendor/*
  - src/Modules/*/Tests/*
tools:
  external_code_coverage:
    timeout: 600    # Timeout in seconds.
  php_mess_detector: true
  php_code_sniffer: true
  sensiolabs_security_checker: true
  php_code_coverage: true
  php_pdepend: true
  php_loc:
    enabled: true
    excluded_dirs: [vendor, tests, src/Modules/*/Tests]
  php_cpd:
    enabled: true
    excluded_dirs: [vendor, tests, src/Modules/*/Tests]
