language: php

dist: bionic

services:
- redis-server

addons:
  mariadb: '10.4'
  hosts:
  - larapie.test
  - api.larapie.test

env:
  global:
  - setup=normal

matrix:
  fast_finish: true
  include:
    - php: '7.2'
    - php: '7.3'

cache:
  directories:
    - $HOME/.composer/cache

before_install:
- mysql -u root -e 'CREATE DATABASE IF NOT EXISTS travis;'
- echo '' > ./storage/logs/laravel.log
- cp .env.travis .env

install:
- pecl uninstall igbinary
- pecl uninstall redis
- pecl install igbinary
- yes | pecl install redis
- travis_retry composer self-update
- composer install

before_script:
- php artisan key:generate

script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi

after_script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
- if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

after_failure:
- echo --------------- Begin > Laravel.log ---------------
- cat storage/logs/laravel.log
- echo --------------- End   > Laravel.log ---------------
